server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # Habilitar Gzip
    gzip on;

    # Nivel de compresión (1-9). 5 o 6 es el equilibrio perfecto entre CPU y ahorro.
    gzip_comp_level 6;

    # No comprimir archivos más pequeños que este tamaño (en bytes)
    gzip_min_length 256;

    # Comprimir incluso si el cliente viene a través de un proxy
    gzip_proxied any;

    # Añadir la cabecera "Vary: Accept-Encoding"
    gzip_vary on;

    # Tipos de archivos a comprimir (Muy importante para tu API y Vue)
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/x-javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;

    # Deshabilitar para navegadores antiguos que no lo soportan bien
    gzip_disable "msie6";
}
