name: Frontend CI/CD (Optimizado)

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest # <--- Compilamos en GitHub (RAM de sobra)
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/

  deploy:
    needs: build
    runs-on: self-hosted # <--- Solo desplegamos en tu servidor
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ${{ secrets.PROD_PATH }}/frontend/dist
      - name: Restart Frontend Container
        run: |
          cd ${{ secrets.PROD_PATH }}
          git config --global --add safe.directory ${{ secrets.PROD_PATH }}
          git pull origin main --no-edit
          COMPOSE_PROFILES=frontend docker compose up -d --build frontend
